// Generated by scripts/landingCatalog.mjs. Do not edit by hand.
export const GENERATED_LANDING_CATALOG = {
  "generatedAt": "2026-07-24T06:26:49.636Z",
  "examCount": 36,
  "activeQuestionCount": 42294,
  "demandPeriod": "115年截至6月底止通過技能檢定學術科測試",
  "featuredExamIds": [
    "forklift-operation-single",
    "occupational-safety-health-management-b",
    "chinese-cooking-meat-c",
    "computer-software-application-c"
  ],
  "exams": [
    {
      "examId": "forklift-operation-single",
      "titleZh": "堆高機操作單一級",
      "code": "15100",
      "level": "單一級",
      "applicantCount": 13467
    },
    {
      "examId": "occupational-safety-health-management-b",
      "titleZh": "職業安全衛生管理乙級",
      "code": "22200",
      "level": "乙級",
      "applicantCount": 12787
    },
    {
      "examId": "chinese-cooking-meat-c",
      "titleZh": "中餐烹調－葷食丙級",
      "code": "07602",
      "level": "丙級",
      "applicantCount": 7408
    },
    {
      "examId": "computer-software-application-c",
      "titleZh": "電腦軟體應用丙級",
      "code": "11800",
      "level": "丙級",
      "applicantCount": 7166
    },
    {
      "examId": "interior-decoration-management-b",
      "titleZh": "建築物室內裝修工程管理乙級",
      "code": "12600",
      "level": "乙級",
      "applicantCount": 6768
    },
    {
      "examId": "childcare-single",
      "titleZh": "托育人員單一級",
      "code": "15400",
      "level": "單一級",
      "applicantCount": 4625
    },
    {
      "examId": "beauty-c",
      "titleZh": "美容丙級",
      "code": "10000",
      "level": "丙級",
      "applicantCount": 4364
    },
    {
      "examId": "beverage-preparation-c",
      "titleZh": "飲料調製丙級",
      "code": "20600",
      "level": "丙級",
      "applicantCount": 4364
    },
    {
      "examId": "computer-software-application-b",
      "titleZh": "電腦軟體應用乙級",
      "code": "11800",
      "level": "乙級",
      "applicantCount": 3187
    },
    {
      "examId": "indoor-wiring-b",
      "titleZh": "室內配線－屋內線路裝修乙級",
      "code": "00700",
      "level": "乙級",
      "applicantCount": 3111
    },
    {
      "examId": "indoor-wiring-c",
      "titleZh": "室內配線－屋內線路裝修丙級",
      "code": "00700",
      "level": "丙級",
      "applicantCount": 2673
    },
    {
      "examId": "industrial-electronics-c",
      "titleZh": "工業電子丙級",
      "code": "02800",
      "level": "丙級",
      "applicantCount": 2587
    },
    {
      "examId": "care-service-single",
      "titleZh": "照顧服務員單一級",
      "code": "17800",
      "level": "單一級",
      "applicantCount": 2462
    },
    {
      "examId": "employment-service-b",
      "titleZh": "就業服務乙級",
      "code": "19500",
      "level": "乙級",
      "applicantCount": 2234
    },
    {
      "examId": "computer-hardware-repair-c",
      "titleZh": "電腦硬體裝修丙級",
      "code": "12000",
      "level": "丙級",
      "applicantCount": 1940
    },
    {
      "examId": "women-hairdressing-c",
      "titleZh": "女子美髮丙級",
      "code": "06700",
      "level": "丙級",
      "applicantCount": 1878
    },
    {
      "examId": "water-pipe-fitting-c",
      "titleZh": "自來水管配管丙級",
      "code": "01600",
      "level": "丙級",
      "applicantCount": 1763
    },
    {
      "examId": "cnc-milling-b",
      "titleZh": "銑床－CNC銑床乙級",
      "code": "18201",
      "level": "乙級",
      "applicantCount": 1615
    },
    {
      "examId": "digital-electronics-b",
      "titleZh": "數位電子乙級",
      "code": "11700",
      "level": "乙級",
      "applicantCount": 1608
    },
    {
      "examId": "excavator-operation-single",
      "titleZh": "重機械操作－挖掘機單一級",
      "code": "07002",
      "level": "單一級",
      "applicantCount": 1544
    },
    {
      "examId": "car-repair-c",
      "titleZh": "汽車修護丙級",
      "code": "02000",
      "level": "丙級",
      "applicantCount": 1473
    },
    {
      "examId": "retail-service-c",
      "titleZh": "門市服務丙級",
      "code": "18100",
      "level": "丙級",
      "applicantCount": 1313
    },
    {
      "examId": "western-cooking-c",
      "titleZh": "西餐烹調丙級",
      "code": "14000",
      "level": "丙級",
      "applicantCount": 1299
    },
    {
      "examId": "occupational-safety-management-a",
      "titleZh": "職業安全管理甲級",
      "code": "22000",
      "level": "甲級",
      "applicantCount": 1175
    },
    {
      "examId": "computer-hardware-repair-b",
      "titleZh": "電腦硬體裝修乙級",
      "code": "12000",
      "level": "乙級",
      "applicantCount": 1146
    },
    {
      "examId": "occupational-hygiene-management-a",
      "titleZh": "職業衛生管理甲級",
      "code": "22100",
      "level": "甲級",
      "applicantCount": 1114
    },
    {
      "examId": "loader-operation-single",
      "titleZh": "重機械操作－鏟裝機單一級",
      "code": "07004",
      "level": "單一級",
      "applicantCount": 1092
    },
    {
      "examId": "motorcycle-repair-c",
      "titleZh": "機器腳踏車修護丙級",
      "code": "14500",
      "level": "丙級",
      "applicantCount": 1048
    },
    {
      "examId": "dining-service-c",
      "titleZh": "餐飲服務丙級",
      "code": "21500",
      "level": "丙級",
      "applicantCount": 986
    },
    {
      "examId": "man-haircut-c",
      "titleZh": "男子理髮丙級",
      "code": "06000",
      "level": "丙級",
      "applicantCount": 973
    },
    {
      "examId": "industrial-wiring-c",
      "titleZh": "工業配線丙級",
      "code": "01300",
      "level": "丙級",
      "applicantCount": 877
    },
    {
      "examId": "electrical-equipment-inspection-c",
      "titleZh": "用電設備檢驗丙級",
      "code": "16600",
      "level": "丙級",
      "applicantCount": 850
    },
    {
      "examId": "heat-treatment-c",
      "titleZh": "熱處理丙級",
      "code": "02100",
      "level": "丙級",
      "applicantCount": 817
    },
    {
      "examId": "web-design-b",
      "titleZh": "網頁設計乙級",
      "code": "17300",
      "level": "乙級",
      "applicantCount": 11
    },
    {
      "examId": "baking-food-c",
      "titleZh": "烘焙食品丙級",
      "code": "07700",
      "level": "丙級",
      "applicantCount": null
    },
    {
      "examId": "accounting-c",
      "titleZh": "會計事務丙級",
      "code": "14900",
      "level": "丙級",
      "applicantCount": null
    }
  ],
  "metaDescription": "升級吧收錄 36 種技術士技能檢定學科題庫，包括堆高機操作單一級、職業安全衛生管理乙級、中餐烹調－葷食丙級、電腦軟體應用丙級。練官方公告題目、錯題複習與計時模擬考；免費、免註冊、可離線。"
} as const
