import { readFile, readdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

function occupationCode(manifest) {
  return manifest.sections.find((section) => section.sourceGroup === 'occupation')?.subjectCode
}

export function buildLandingCatalog(manifests, demand, featuredCount = 4) {
  const demandByKey = new Map(demand.ranking.map((entry) => [`${entry.code}:${entry.level}`, entry]))
  const ranked = manifests.map((manifest) => {
    const code = occupationCode(manifest)
    const stats = demandByKey.get(`${code}:${manifest.level}`)
    return {
      examId: manifest.examId,
      titleZh: manifest.titleZh,
      code,
      level: manifest.level,
      applicantCount: stats?.applicantCount ?? null,
    }
  }).sort((a, b) => (
    (b.applicantCount ?? -1) - (a.applicantCount ?? -1)
    || a.titleZh.localeCompare(b.titleZh, 'zh-Hant-TW')
  ))
  const featured = ranked.slice(0, featuredCount)
  const featuredNames = featured.map((entry) => entry.titleZh).join('、')
  return {
    generatedAt: new Date().toISOString(),
    examCount: manifests.length,
    activeQuestionCount: manifests.reduce((total, manifest) => total + manifest.activeQuestionCount, 0),
    demandPeriod: demand.period,
    featuredExamIds: featured.map((entry) => entry.examId),
    exams: ranked,
    metaDescription: `升級吧收錄 ${manifests.length} 種技術士技能檢定學科題庫，包括${featuredNames}。練官方公告題目、錯題複習與計時模擬考；免費、免註冊、可離線。`,
  }
}

async function main() {
  const root = new URL('../public/data/exams/', import.meta.url)
  const manifests = await Promise.all((await readdir(root)).map(async (directory) => (
    JSON.parse(await readFile(new URL(`${directory}/manifest.json`, root), 'utf8'))
  )))
  const demand = JSON.parse(await readFile(new URL('../source/wda-demand-ranking.json', import.meta.url), 'utf8'))
  const catalog = buildLandingCatalog(manifests, demand)
  await writeFile(new URL('../source/landing-catalog.json', import.meta.url), `${JSON.stringify(catalog, null, 2)}\n`)
  await writeFile(
    new URL('../src/app/generatedLandingCatalog.ts', import.meta.url),
    `// Generated by scripts/landingCatalog.mjs. Do not edit by hand.\nexport const GENERATED_LANDING_CATALOG = ${JSON.stringify(catalog, null, 2)} as const\n`,
  )
  console.log(`Landing: ${catalog.examCount} exams; ${catalog.activeQuestionCount} active questions; featured ${catalog.featuredExamIds.join(', ')}`)
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === fileURLToPath(new URL(process.argv[1], `file://${process.cwd()}/`))
if (isMain) await main()
