// PDF text extraction inserted stray spaces into English/identifier terms
// (e.g. "Mic rosoft", "An droid"). These are exact broken→fixed strings,
// applied with word boundaries so they cannot corrupt unrelated text.
// Legitimately-spaced terms (GROUP BY, Mac OS, Class C, Wide Area Network,
// We Heart It, etc.) are deliberately NOT included.
export const CORRECTIONS = {
  'A pp': 'App',
  'A pplication Layer': 'Application Layer',
  'Access Co ntrol': 'Access Control',
  'Access Contr ol': 'Access Control',
  'An droid': 'Android',
  'Anonymo us': 'Anonymous',
  'Apac he Server': 'Apache Server',
  'Apa che Server': 'Apache Server',
  'Arr ay': 'Array',
  'Atomic Valu e': 'Atomic Value',
  'Authorization Rule s': 'Authorization Rules',
  'B ooks': 'Books',
  'B ridge': 'Bridge',
  'Ba d SQL': 'Bad SQL',
  'Big D ata': 'Big Data',
  'BlackB erry OS': 'BlackBerry OS',
  'Cascading Style S heets': 'Cascading Style Sheets',
  'Co nsistency': 'Consistency',
  'Connectionles s': 'Connectionless',
  'D ata Link': 'Data Link',
  'D ebian': 'Debian',
  'DELET E VIEW': 'DELETE VIEW',
  'Disassembl er': 'Disassembler',
  'Document Object Mo del': 'Document Object Model',
  'F oreign Key': 'Foreign Key',
  'FO RTRAN': 'FORTRAN',
  'Facebo ok': 'Facebook',
  'Field Va lue': 'Field Value',
  'Fu nctional Dependent': 'Functional Dependent',
  'G oogle Maps': 'Google Maps',
  'Goo gle': 'Google',
  'Google Do cuments': 'Google Documents',
  'Google Ea rth': 'Google Earth',
  'iGoo gle': 'iGoogle',
  'I mported Style Sheet': 'Imported Style Sheet',
  'I nformation Service': 'Information Service',
  'Imported Style She et': 'Imported Style Sheet',
  'Inline Styl e': 'Inline Style',
  'Maria DB': 'MariaDB',
  'MariaD B': 'MariaDB',
  'Microsoft Hy per': 'Microsoft Hyper',
  'Mic rosoft': 'Microsoft',
  'Mod ulation': 'Modulation',
  'Mozilla Firef ox': 'Mozilla Firefox',
  'Mult i': 'Multi',
  'Multiple Collision Domain s': 'Multiple Collision Domains',
  'Ne twork': 'Network',
  'No de': 'Node',
  'Ou tputCache': 'OutputCache',
  'P aint': 'Paint',
  'P erformance': 'Performance',
  'Presentat ion Layer': 'Presentation Layer',
  'Physic al': 'Physical',
  'Physical Lay er': 'Physical Layer',
  'Proce ss Scheduling': 'Process Scheduling',
  'Program loggin g': 'Program logging',
  'Prox y': 'Proxy',
  'Ra ce Condition': 'Race Condition',
  'Schedu ler': 'Scheduler',
  'S upervisory Control And Data Acquisition': 'Supervisory Control And Data Acquisition',
  'S ymbian': 'Symbian',
  'Sym bian OS': 'Symbian OS',
  'SE LECT Dept': 'SELECT Dept',
  'Dept no': 'Deptno',
  'IN TEGER': 'INTEGER',
  'De pt': 'Dept',
  'G ROUP': 'GROUP',
  'C omm': 'Comm',
  'Book s': 'Books',
  'Ser vice': 'Service',
  'Authenticati on': 'Authentication',
  'B2 C': 'B2C',
  'M P3': 'MP3',
  'O gg': 'Ogg',
  'NOTNU LL': 'NOT NULL',
  'on Unload': 'onUnload',
  'a ttachment': 'attachment',
  'abcde fg': 'abcdefg',
  'ar rary': 'array',
  'ge tmygid': 'getmygid',
  'us ermanager': 'usermanager',
  'CO 2': 'CO2',
  'CH 4': 'CH4',
  'N 2 O': 'N2O',
  'SF 6': 'SF6',
  'O 2': 'O2',
  'O 3': 'O3',
  'Salar y': 'Salary',
  'Segme nt': 'Segment',
  'Serve r': 'Server',
  'Sh ortest': 'Shortest',
  'SharePoi nt': 'SharePoint',
  'SharePoin t': 'SharePoint',
  'Stored Procedu re': 'Stored Procedure',
  'T aget Frame': 'Target Frame',
  'T ag': 'Tag',
  'Ta b': 'Tab',
  'Thrashin g': 'Thrashing',
  'Tr ansport Layer': 'Transport Layer',
  'Transpor t Layer': 'Transport Layer',
  'Twitte r': 'Twitter',
  'Uni cast': 'Unicast',
  'Video Co nference': 'Video Conference',
  'W 3C': 'W3C',
  'Wi de Area Network': 'Wide Area Network',
  'Wi ndows 10': 'Windows 10',
  'Windows Se rver': 'Windows Server',
  'Yaho o': 'Yahoo',
  'aLin k': 'aLink',
  'c hdir': 'chdir',
  'c lass': 'class',
  'c pio': 'cpio',
  'chkd sk': 'chkdsk',
  'createdi r': 'createdir',
  'de fine': 'define',
  'dis play': 'display',
  'e Mule': 'eMule',
  'e mail': 'email',
  'e scaped character': 'escaped character',
  'Exc lusion': 'Exclusion',
  'ex ists': 'exists',
  'floatv al': 'floatval',
  'fo nt': 'font',
  'fon t': 'font',
  'g etElementById': 'getElementById',
  'getElementsByClassNam e': 'getElementsByClassName',
  'i ni': 'ini',
  'ima ge': 'image',
  'l ocalhost': 'localhost',
  'lis t': 'list',
  'manage r': 'manager',
  'me thods': 'methods',
  'mo unt': 'mount',
  'myBre ak': 'myBreak',
  'mys ql': 'mysql',
  'n etstat': 'netstat',
  'na me': 'name',
  'nu m': 'num',
  'p roperties': 'properties',
  's etting': 'setting',
  'sh ow': 'show',
  'sho w': 'show',
  't extbox': 'textbox',
  't ransform': 'transform',
  'u pdate': 'update',
  'updat e': 'update',
  'voi d': 'void',
  'w idth': 'width',
  'w mf': 'wmf',
}

// Splits next to punctuation/underscores where \b can't help. These broken
// strings are unique enough to replace literally (verified in the bank).
const RAW_CORRECTIONS = {
  '$_SESSIO N': '$_SESSION',
  '_na me': '_name',
  '_manage r': '_manager',
  'mys ql': 'mysql',
  'TABLE t able': 'TABLE table',
  'ANDSUM': 'AND SUM',
  'PM 2 . 5': 'PM2.5',
  'W/m 2': 'W/m²',
  'μg/m 3': 'μg/m³',
}

const PATTERNS = Object.entries(CORRECTIONS).map(([broken, fixed]) => [
  new RegExp(`\\b${broken.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'g'),
  fixed,
])

export function sanitizeText(text) {
  if (typeof text !== 'string') return text
  let out = text
  for (const [re, fixed] of PATTERNS) out = out.replace(re, fixed)
  for (const [broken, fixed] of Object.entries(RAW_CORRECTIONS)) out = out.split(broken).join(fixed)
  return out
}
